### ISSUE TITLE
how to use main wechat API?

### ISSUE THREAD

**Issue by dcsan** [raohuaming/meteor-wechat-js#1]
I understand this repo deals with getting and refreshing tokens, but is there a way to use the main WeChat API?

eg how to receive and reply to messages?

**Comment by raohuaming** [comment]
You should probably check out wechat official doc for that use: http://mp.weixin.qq.com/wiki/14/89b871b5466b19b3efa4ada8e577d45e.html.

This lib has wrapped the official js lib, but aimed at making the authentication process easier in Meter app.

Besides, as far as know, you should create an wechat developer account on https://mp.weixin.qq.com. But not all of the API are open to all developers. You should also apply for some certifications to use some of the API.

**Comment by dcsan** [comment]
thanks for the info! Yes, getting a wechat official account outside china seems a bit complicated... >.<

**Comment by raohuaming** [comment]
yes, even if it is in China it is also complicated, especially for payment API.
