### ISSUE TITLE
Timestamp should be in 10 digits instead of 13 digits

### ISSUE THREAD

**Issue by dotgreg** [raohuaming/meteor-wechat-js#3]
Thanks for that great plugin, really helpful!

Wechat JS SDK is accepting only 10 digits timestamps (on seconds). The date.now() used is generating a timestamp on 13 digits (in milliseconds) so it does not generate the right signature. Tested with http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=jsapisign.

I just proposed a pull

**Comment by raohuaming** [comment]
@dotgreg Thanks, I just merged your PR and published a new version in atmospherejs.com.
